### ISSUE TITLE
Escape procedure if no tweets are found

### ISSUE THREAD

**Issue by Nebelhom** [Nebelhom/tweetery#72]
If no tweets download the following error occurs:

`
Traceback (most recent call last):
  File "main.py", line 32, in <module>
    tc.predict()
  File "/home/nebelhom/tweetery/classifier.py", line 263, in predict
    self.prediction = self.clf.predict(self.clf_text)
  File "/home/nebelhom/anaconda3/envs/Tweetery/lib/python3.6/site-packages/sklearn/utils/metaestimators.py", line 115, in <lambda>
    out = lambda *args, **kwargs: self.fn(obj, *args, **kwargs)
  File "/home/nebelhom/anaconda3/envs/Tweetery/lib/python3.6/site-packages/sklearn/pipeline.py", line 306, in predict
    Xt = transform.transform(Xt)
  File "/home/nebelhom/anaconda3/envs/Tweetery/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 1410, in transform
    return self._tfidf.transform(X, copy=False)
  File "/home/nebelhom/anaconda3/envs/Tweetery/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 1114, in transform
    X = normalize(X, norm=self.norm, copy=False)
  File "/home/nebelhom/anaconda3/envs/Tweetery/lib/python3.6/site-packages/sklearn/preprocessing/data.py", line 1412, in normalize
    estimator='the normalize function', dtype=FLOAT_DTYPES)
  File "/home/nebelhom/anaconda3/envs/Tweetery/lib/python3.6/site-packages/sklearn/utils/validation.py", line 462, in check_array
    context))
ValueError: Found array with 0 sample(s) (shape=(0, 4160)) while a minimum of 1 is required by the normalize function.
`

**Comment by Nebelhom** [comment]
Write a custom Exception that checks if len of download tweets is 0. If so, raise the exception with a remark. This will stop the process.
