### ISSUE TITLE
reporttxt throws an error

### ISSUE THREAD

**Issue by Nebelhom** [Nebelhom/tweetery#85]
When using `reporttxt` in `TweetClassifier` class of `classifier.py`, an error is thrown. See Traceback below:

```
Traceback (most recent call last):
  File "main.py", line 44, in <module>
    tc.save_as_txt(fname=env_args['reporttxt'])
  File "Z:\Private\GitHub\tweetery\classifier.py", line 422, in save_as_txt
    url=url, date=date))
  File "C:\Users\Be11341\AppData\Local\Continuum\anaconda3\envs\twitter\lib\enco
dings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0142' in position
89: character maps to <undefined>
```

**Comment by Nebelhom** [comment]
Leave a comment
